const kz = {
  common: {
    selectedLanguage: "Қазақша",
    error: "Бірдеңе дұрыс болмады!",
    meters: "м",
    empty: "Әлі қолжетімді емес",
    refresh: "Жаңарту",
    next: "Кейін",
    back: "Артқа",
    close: "Жабу",
    confirm: "Растау",
    cancel: "Бас тарту",
    understand: "Түсінікті",
    check: "Тексеру",
    warning: "Ескерту!",
    notification: "Хабарландыру",
    unknown: "Белгісіз",
    guest: "Тұтынушы:",
    phone: "Телефон",
    login: "Кіру",
    logout: "Шығу",
    settings: "Баптаулар",
    language: "Тіл",
    feedback: "Кері байланыс",
    feedbacks: "Пікірлер",
    all: "Барлығы",
    unread: "Оқылмаған",
    allRead: "Барлығын оқыдыңыз!",
    determining: "анықталуда...",
    call: "Қоңырау шалу",
    pcs: "дана",
    navigator: "Навигатор",
    minutesShort: "мин",
    search: "Іздеу",
    selectCountry: "Мемлекетті таңдаңыз",
    selectDate: "Күнді таңдаңыз",
    year: "Жыл",
    month: "Ай",
    loading: "Жүктелуде...",
    error: {
      status: "Бірдеңе қате кетті, күйі:",
      network:
        "Интернет мәселесі. Деректерді алу мүмкін емес. Интернетті тексеріңіз!",
      gps: "GPS мәселесі. Деректерді алу мүмкін емес. GPS-ті қосып, қайта көріңіз!",
      data: "Қате. Деректерді алу мүмкін емес. Интернетті тексеріп, жаңартып көріңіз!",
    },
    currency: {
      tenge: "теңге",
      sum: "сум",
    },
    fakeGps: {
      title: "Жалған GPS анықталды",
      description:
        "Құрылғыңызда жалған GPS немесе орналасуды бұрмалайтын қосымша анықталды. Бұл жеткізу ережелеріне қайшы және қызмет сапасына әсер етеді.",
      exitButton: "Қосымшадан шығу",
      instructions: {
        title: "Курьер қосымшасын жалғастыру үшін:",
        step1: "Жалған GPS немесе орналасу қолданбаларын өшіріңіз.",
        step2: "Құрылғыны қайта іске қосыңыз.",
        step3: "Курьер қосымшасын қайта ашыңыз.",
      },
    },
    gps: {
      requestTitle: "Геолокация сұрауы",
      permissionDescription:
        "Қосымшаның жақсы жұмыс істеуі және дәлірек ұсыныстар алу үшін сізден орналасқан жеріңізге рұқсат беруіңізді сұраймыз. Орналасу деректеріңіз тек қосымша ішінде қолданылады және үшінші тұлғаларға берілмейді.",
      missing: "Сіз радардан жоғалып кеттіңіз, өтінеміз, GPS-ті қосыңыз!",
      turnOn: "GPS-ті қосу",
    },
  },
  datetime: {
    months: {
      january: "Қаңтар",
      february: "Ақпан",
      march: "Наурыз",
      april: "Сәуір",
      may: "Мамыр",
      june: "Маусым",
      july: "Шілде",
      august: "Тамыз",
      september: "Қыркүйек",
      october: "Қазан",
      november: "Қараша",
      december: "Желтоқсан",
    },
    days: {
      sun: "Жс",
      mon: "Дс",
      tue: "Сс",
      wed: "Ср",
      thu: "Бс",
      fri: "Жм",
      sat: "Сб",
    },
    today: "Бүгін",
    date: "Дата",
  },
  orders: {
    title: "Тапсырыстар",
    activeTitle: "Белсенді тапсырыстар",
    active: "Белсенді",
    other: "Басқа тапсырыстар",
    closedOrders: "Жабық тапсырыстар",
    closed: "Жабық",
    averageDeliveryTime: "Орташа жеткізу уақыты",
    delivered: "Жеткізілгендер",
    empty: "Сізде әлі тапсырыс жоқ.",
    emptyMessage:
      "Сізде әлі тапсырыс жоқ екенін байқадық. Бұл біраз көңілсіз болуы мүмкін, бірақ уайымдамаңыз, жақында жаңа тапсырыстар келеді.",
    emptyRefresh: "Тізім бос, бетті жаңартыңыз",
    status: {
      delivered: "Жеткізілді",
      arrived: "Келіп жетті",
      onWay: "Жолда",
      delayed: "Кейінге қалдырылды",
      preparing: "Дайындалып жатыр",
      ready: "Дайын",
      preparingMessage: "Тапсырыс дайындалып жатыр, дайындығының соңын күтіңіз",
      checkAndStart:
        "Тапсырыстың позицияларын тексеріп, тапсырысты жеткізуді бастаңыз",
    },
    queueWarning:
      "Тапсырысты өңдеуге бір минут уақытыңыз бар, содан кейін ол өзгермейді",
    pressAtBranch:
      "Тапсырыс қабылданді бастау үшін «Мен филиалдамын» түймесін басыңыз",
    timer: "Тапсырыс таймері:",
    order: "Тапсырыс",
    total: "Жалпы:",
    address: "Мекенжай:",
    house: "Үй:",
    apartment: "Пәтер:",
    entrance: "Кіреберіс:",
    floor: "Қабат:",
    intercom: "Домофон коды:",
    channel: "Тапсырыс көзі",
    paymentAmount: "Төлем сомасы:",
    paymentMethod: "Төлем әдісі:",
    paymentIndicatorPaid: "Төленген",
    paymentIndicatorNotPaid: "Төленбеген",
    noComments: "Түсіндірмесіз:",
    comment: "Түсініктеме",
    printTime: "Тапсырыс уақыты",
    deliveryTime: "Жеткізу уақыты",
    startTime: "Басталу уақыты:",
    endTime: "Аяқталу уақыты:",
    addressChanged: "Мекенжай сәтті өзгертілді",
    addressError:
      "Клиенттің мекенжайын өзгерту кезінде қате пайда болды, сұранысты қайталаңыз",
    changeAddress: "Мекенжайды өзгерту",
    addressWarning:
      "Мекенжайдың өзгеруін оператор тексереді және оны бір тапсырысқа бір рет өзгертуге болады.",
    showRoute: "Маршрутты көрсету",
    arrive: "Келіп жетті",
    complete: "Аяқтау",
    delay: "Кейінге қалдыру",
    startJourney: "Жолға шығу",
    delayWarning:
      "Тапсырыс %{allowedDelayedTime} минуттан астам уақытқа «Кейінге қалдырылды». Тапсырыстарды қабылдауды жалғастыру үшін ағымдағы тапсырыс(тар)ды тұтынушыға жеткізіңіз немесе филиал менеджеріне хабарласыңыз.",
    finishDelayed: "Кейінге қалдырылған тапсырыстарды аяқтаңыз",
    delayLimitWarning:
      'Тапсырыс "Кейінге қалдырылды" күйінде %{time} минуттан артық болуы мүмкін емес. Сондай-ақ, кешіктірілген тапсырыстардың максималды саны - %{count} дана.',
    deliveredIn: "Жеткізілді",
    courierReady: "Курьер тапсырысты алуға дайын",
    finishDelivery: "Жеткізуді аяқтау",
    atBranch: "Мен филиалдамын",
    distanceFromPoint: "Нүктеден нақты радиус",
    notInRadius: "Сіз клиент радиуста емессіз",
  },
  profile: {
    status: {
      notInBranch: "Сіз әлі өз филиалыңызға жетпедіңіз",
    },
  },
  payment: {
    title: "Төлем",
    myPayments: "Менің төлемдерім",
    selectType: "Төлем түрін таңдаңыз",
    cash: "Қолма-қол ақша",
    terminal: "Терминал",
    cards: "Карталар",
    toCashier: "Кассаға:",
    page: "Төлем беті",
    success: "Төлем клиент тарапынан сәтті аяқталды",
    qrInstruction: "Клиентке төлем жасау үшін QR-кодты ұсыныңыз",
    processing:
      "Сіздің сұранысыңыз орындалуда, процесс аяқталғанын тексеріңіз!",
    continueOrder: "Жалғастыру үшін тапсырысқа өтіңіз!",
    smsSent:
      "Сондай-ақ, клиенттің нөміріне төлем туралы ақпаратпен SMS жіберілді.",
    changeType: "Төлем түрін өзгерту",
    fixed: "Фикса",
    tips: "Чайлық",
    bonus: "Бонус",
    penalty: "Айыппұл",
    amount: "Сома",
  },
  profile: {
    title: "Профиль",
    language: "Тіл",
    rating: "Сіздің рейтингіңіз",
    branch: "Сіздің филиалыңыз:",
    distanceLeft: "Қалғаны:",
    selectBranch: "Филиалды таңдаңыз",
    changeBranch: "Филиалды ауыстыру",
    training: "Оқу",
    allCourses: "Барлық курстар",
    courseRequired:
      "Сізге iSpring платформасында курс бекітілген. Осы курсты өткеннен кейін бағдарламаны пайдалана аласыз!",
    status: {
      notStarted: "Басталған жоқ",
      inProgress: "Үдерісте",
      waiting: "Күтілуде",
      completed: "Аяқталды",
      passed: "Тапсырылды",
      incomplete: "Толық емес",
      failed: "Сәтсіз",
      rejected: "Қабылданбады",
      unknown: "Белгісіз",
      offline: "Жұмыс істемейді",
      onWay: "Жолда",
      onSite: "Етіб келді",
      returning: "Қайтып келеді",
      assigned: "Біріктелген",
      free: "Бос",
    },
    networkMonitoring: "Желі мониторингі",
    determining: "Анықталуда...",
    numberDetermining: "Нөмір анықталуда...",
    endShift: "Ауысымды жабу",
    activeOrdersWarning: "Сізде белсенді тапсырыстар бар!",
    enterSmsCode: "SMS арқылы алынған кодты енгізіңіз:",
    smsCodeSent: "Pin-код телефоныңызға жіберілді, оны қайта тексеріңіз",
    enterDifferentNumber: "Басқа нөмірді енгізу",
    pushError: "Push хабарлама үшін токен алу сәтсіз аяқталды!",
    contactOperator: "Тапсырыс бойынша операторға хабарласу",
    noNearbyBranches:
      "Сізден 150 м радиуста филиалдар жоқ. Филиалды өзгерту үшін филиал радиусында болуыңыз керек",
    organizationsNotFound: "Ұйымдар табылмады",
    nearestBranches: "Сіздің орналасқан жеріңізге жақын филиалдар",
    generalStats: "Жалпы статистика",
    averageRating: "%{reviewCount} пікір үшін орташа рейтинг",
    ratingsAndCategories: "Бағалар мен санаттар",
    total: "Жалпы саны",
    noRatingsWithScore: "Бұл бағамен пікірлер жоқ",
    noRatingsForPeriod: "Бұл кезең үшін пікірлер жоқ",
    organizationChanged: "Филиал сәтті өзгертілді",
  },
  welcome: {
    title: "Қош келдіңіз!",
    motivation_quote:
      "Егер бір нәрсеге қабілетті екеніңізге сенсеңіз, сіз дұрыссыз; егер ештеңе шықпайды деп ойласаңыз, ол да дұрыс.",
  },
};

const ru = {
  common: {
    selectedLanguage: "Русский",
    error: "Что то случилось не так!",
    error: {
      status: "Что-то пошло не так, Cтатус:",
      network:
        "Проблемы с интернетом. Невозможно получить данные. Проверьте интернет!",
      gps: "Проблемы с GPS. Невозможно получить данные. Включите GPS, и попробуйте заново!",
      data: "Ошибка. Невозможно получить данные. Проверьте интернет и попробуйте обновить",
    },
    meters: "м",
    loading: "Загрузка...",
    empty: "Здесь пока пусто",
    refresh: "Обновить",
    next: "Далее",
    back: "Назад",
    close: "Закрыть",
    confirm: "Подвердить",
    cancel: "Отменить",
    understand: "Понятно",
    check: "Проверить",
    warning: "Предупреждение!",
    notification: "Уведомление",
    unknown: "Неизвестно",
    guest: "Гость:",
    phone: "Телефон",
    login: "Войти",
    logout: "Выйти",
    settings: "Настройки",
    language: "Язык",
    feedback: "Обратная связь",
    feedbacks: "Отзывы",
    all: "Все",
    unread: "Непрочитано",
    allRead: "Вы все прочитали!",
    determining: "определяется...",
    call: "Позвонить",
    pcs: "шт",
    currency: {
      tenge: "тенге",
      sum: "сум",
    },
    navigator: "Навигатор",
    minutesShort: "мин",
    search: "Поиск",
    selectCountry: "Выберите страну",
    fakeGps: {
      title: "Обнаружено использование поддельного GPS",
      description:
        "Мы обнаружили, что на вашем устройстве используется поддельный GPS или приложение для подмены местоположения. Это нарушает правила доставки и влияет на надежность сервиса.",
      instructions: {
        title: "Чтобы продолжить использование приложения курьера:",
        step1: "Отключите все приложения, подменяющие местоположение.",
        step2: "Перезапустите устройство для восстановления точного GPS.",
        step3: "Заново откройте приложение курьера.",
      },
      exitButton: "Выйти из приложения",
    },
    gps: {
      requestTitle: "Запрос геолокации",
      permissionDescription:
        "Для лучшей работы приложения и получения более точных рекомендаций мы просим вас разрешить доступ к вашему местоположению. Данные о местоположении будут использоваться только внутри приложения и не будут передаваться третьим лицам.",
      missing: "Вы пропали с радара, пожалуйста, включите GPS!",
      turnOn: "Включить GPS",
    },
    selectDate: "Выберите дату",
    year: "Год",
    month: "Месяц",
  },
  datetime: {
    months: {
      january: "Январь",
      february: "Февраль",
      march: "Март",
      april: "Апрель",
      may: "Май",
      june: "Июнь",
      july: "Июль",
      august: "Август",
      september: "Сентябрь",
      october: "Октябрь",
      november: "Ноябрь",
      december: "Декабрь",
    },
    days: {
      sun: "Вс",
      mon: "Пн",
      tue: "Вт",
      wed: "Ср",
      thu: "Чт",
      fri: "Пт",
      sat: "Сб",
    },
    today: "сегодня",
    date: "Дата",
  },
  orders: {
    title: "Заказы",
    activeTitle: "Активные Заказы",
    active: "Активные",
    other: "Другые заказы",
    closedOrders: "Закрытые заказы",
    closed: "Закрытые",
    averageDeliveryTime: "Среднее время доставки",
    delivered: "Доставленные",
    empty: "У вас еще нет доступных заказов",
    emptyMessage:
      "Мы обратили внимание, что у вас пока нет доступных заказов. Мы понимаем, что это может вызвать некоторое разочарование, но не волнуйтесь, новые заказы скоро появятся.",
    emptyRefresh: "Список пуст обновите страницу",
    status: {
      delivered: "Доставлен",
      arrived: "Прибыл",
      onWay: "В пути",
      delayed: "Отложено",
      preparing: "Готовится",
      ready: "Готов",
      preparingMessage: "Заказ готовится, ожидайте конца готовки",
      checkAndStart: "Проверьте позиции заказа и начните доставку заказа",
    },
    queueWarning:
      "У вас минута чтобы отредактировать порядок заказов, после оно останется таким же",
    pressAtBranch: 'Для получения заказов нажмите на кнопку "Я в филиале"',
    timer: "Таймер заказа:",
    order: "Заказ",
    total: "Общая:",
    address: "Адрес:",
    house: "Дом:",
    apartment: "Квартира:",
    entrance: "Подезд:",
    floor: "Этаж:",
    intercom: "Код от домофона",
    channel: "Канал заказа",
    paymentAmount: "Сумма оплаты",
    paymentMethod: "Способ оплаты",
    paymentIndicatorPaid: "Оплачено",
    paymentIndicatorNotPaid: "Не оплачено",
    noComments: "Без комментарый",
    comment: "Коммент",
    printTime: "Время печати",
    deliveryTime: "Время доставки",
    startTime: "Время начала:",
    endTime: "Время окончания:",
    addressChanged: "Адрес был успешно изменен",
    addressError:
      "Возникла ошибка с изменением адреса клиента, повторите запрос",
    changeAddress: "Изменить адрес",
    addressWarning:
      "Изменение адреса проверяется оператором, и для каждого заказа адрес может быть изменён только один раз",
    showRoute: "Показать маршрут",
    arrive: "Прибыл",
    complete: "Завершить",
    delay: "Отложить",
    startJourney: "Отправиться в путь",
    delayWarning:
      "Заказ «Отложен» более чем на %{allowedDelayedTime} минут. Чтобы продолжить прием заказов, доставьте текущий заказ(-ы) клиенту или свяжитесь с руководителем филиала",
    finishDelayed: "Закончите отложенные заказы",
    delayLimitWarning:
      "Заказ не может находится в статусе отложена более чем %{time} минутов. \n А так же максимальное количество отложенных - %{count} шт.",
    deliveredIn: "Доставлен за",
    courierReady: "Курер готов взять заказ",
    finishDelivery: "Закончить доставку",
    atBranch: "Я в филиале",
    distanceFromPoint: "Фактический радиус от точки",
    notInRadius: "Вы не находитесь в радиусе клиента",
  },
  profile: {
    status: {
      notInBranch: "Вы еще не доехали до своего филиала",
    },
  },
  payment: {
    title: "Оплата",
    myPayments: "Мои платежы",
    selectType: "Выберите тип оплаты",
    cash: "Наличные",
    terminal: "Терминал",
    cards: "Карты",
    toCashier: "В кассу:",
    page: "Страница оплаты",
    success: "Платеж успешно завершен клиентом",
    qrInstruction: "Предоставьте клиенту QR-код для проведения оплаты",
    processing: "Ваш запрос выполняется, проверьте, завершен ли процесс!",
    continueOrder: "Пожалуйста, для продолжения перейдите к заказу!",
    smsSent:
      "Также отправлено SMS-сообщение на номер клиента с информацией для оплаты.",
    changeType: "Cмена типа платежа",
    fixed: "Фикса",
    tips: "Чаевые",
    bonus: "Бонус",
    penalty: "Штраф",
    amount: "Сумма",
  },
  profile: {
    title: "Профиль",
    language: "Язык",
    rating: "Ваш рейтинг",
    branch: "Ваш филиал:",
    distanceLeft: "Вам осталось:",
    selectBranch: "Выберите филиал",
    changeBranch: "Смена филиала",
    training: "Обучение",
    allCourses: "Все курсы",
    courseRequired:
      "К вам прикреплен курс на платформе iSpring. Вы сможете использовать программу после прохождения этого курса!",
    status: {
      notStarted: "Не начался",
      inProgress: "В процессе",
      waiting: "Ожидаеться",
      completed: "Завершено",
      passed: "Сдано",
      incomplete: "Неполное",
      failed: "Неудачно",
      rejected: "Отклонено",
      unknown: "Неизвестно",
      offline: "Вне работе",
      onWay: "В пути",
      onSite: "На месте",
      returning: "Возвращается",
      assigned: "Назначен",
      free: "Свободный",
    },
    networkMonitoring: "Мониторинг сети",
    determining: "Опрелеяеться...",
    numberDetermining: "номер определяется...",
    endShift: "Закрытие смены",
    activeOrdersWarning: "У вас есть активные заказы!",
    enterSmsCode: "Введите код получен в виде СМС:",
    smsCodeSent:
      "Pin-код уже был отправлен на ваш телефон, пожалуйста, проверьте его еще раз",
    enterDifferentNumber: "Ввести другой номер",
    pushError: "Failed to get a push token for push notification!",
    contactOperator: "Связаться с оператором по поводу заказа",
    noNearbyBranches:
      "В радиусе 150 м от вас нет филиалов. Чтобы сменить филиал, вы должны находиться в радиусе филиала",
    organizationsNotFound: "Организации не найдены",
    nearestBranches: "Ближайшие филиалы рядом с вашим местоположением",
    generalStats: "Общая статистика",
    averageRating: "средний рейтинг за %{reviewCount} отзывов",
    ratingsAndCategories: "Оценки и категории",
    total: "Общее кол-во",
    noRatingsWithScore: "Отзывов с этой оценкой нет",
    noRatingsForPeriod: "За этот период отзывов нет",
    organizationChanged: "Организация успешно изменена",
  },
  welcome: {
    title: "Добро пожаловать",
    motivationQuote:
      "Если вы думаете, что на что-то способны, вы правы; если думаете, что у вас ничего не получится - вы тоже правы.",
  },
};

const uz = {
  common: {
    selectedLanguage: "O'zbek",
    error: "Nimadir noto'g'ri bo'ldi!",
    error: {
      status: "Nimadir noto'g'ri ketdi, holati:",
      network:
        "Internet muammosi. Ma'lumotlarni olish imkonsiz. Internetni tekshiring!",
      gps: "GPS muammosi. Ma'lumotlarni olish imkonsiz. GPS ni yoqing va qayta urinib ko'ring!",
      data: "Xato. Ma'lumotlarni olish imkonsiz. Internetni tekshiring va yangilashga urinib ko'ring",
    },
    meters: "m",
    loading: "Yuklanmoqda...",
    empty: "Hozircha bo'sh",
    refresh: "Yangilash",
    next: "Keyingi",
    back: "Orqaga",
    close: "Yopish",
    confirm: "Tasdiqlash",
    cancel: "Bekor qilish",
    understand: "Tushundim",
    check: "Tekshirish",
    warning: "Ogohlantirish!",
    notification: "Bildirishnoma",
    unknown: "Noma'lum",
    guest: "Buyurtmachi:",
    phone: "Telefon",
    login: "Kirish",
    logout: "Chiqish",
    settings: "Sozlanmalar",
    language: "Til",
    feedback: "Fikr-mulohaza",
    feedbacks: "Sharhlar",
    all: "Hammasi",
    unread: "O'qilmagan",
    allRead: "Hammasini o'qidingiz!",
    determining: "aniqlanmoqda...",
    call: "Qo'ng'iroq qilish",
    pcs: "dona",
    currency: {
      tenge: "tenge",
      sum: "so'm",
    },
    navigator: "Navigator",
    minutesShort: "daq",
    search: "Qidirish",
    selectCountry: "Davlatni tanlang",
    fakeGps: {
      title: "Soxta GPS aniqlandi",
      description:
        "Qurilmangizda soxta GPS yoki joylashuvni oʻzgartiruvchi ilova aniqlandi. Bu yetkazib berish qoidalariga zid va xizmat sifatiga salbiy ta'sir qiladi.",
      instructions: {
        title: "Kuryer ilovasidan foydalanishni davom ettirish uchun:",
        step1: "Barcha soxta GPS yoki joylashuv ilovalarini o'chiring.",
        step2: "Qurilmangizni qayta ishga tushiring.",
        step3: "Kuryer ilovasini qaytadan oching.",
      },
      exitButton: "Ilovadan chiqish",
    },
    gps: {
      requestTitle: "Geolokatsiya so'rovi",
      permissionDescription:
        "Ilovaning yaxshi ishlashi va aniqroq tavsiyalar olishi uchun sizdan joylashuvingizga ruxsat berishingizni so'raymiz. Joylashuv ma'lumotlaringiz faqat ilova ichida qo'llaniladi va uchinchi shaxslarga ulashilmaydi.",
      missing: "Siz radardan yo'qolib qoldingiz, iltimos GPSni yoqing!",
      turnOn: "GPS ni yoqish",
    },
    selectDate: "Sana tanlang",
    year: "Yil",
    month: "Oy",
  },
  datetime: {
    months: {
      january: "Yanvar",
      february: "Fevral",
      march: "Mart",
      april: "Aprel",
      may: "May",
      june: "Iyun",
      july: "Iyul",
      august: "Avgust",
      september: "Sentabr",
      october: "Oktabr",
      november: "Noyabr",
      december: "Dekabr",
    },
    days: {
      sun: "Ya",
      mon: "Du",
      tue: "Se",
      wed: "Ch",
      thu: "Pa",
      fri: "Ju",
      sat: "Sh",
    },
    today: "Bugun",
    date: "Sana",
  },
  orders: {
    title: "Buyurtmalar",
    activeTitle: "Faol buyurtmalar",
    active: "Faol",
    other: "Boshqa buyurtmalar",
    closedOrders: "Yopilgan buyurtmalar",
    closed: "Yopilgan",
    averageDeliveryTime: "O'rtacha yetkazish vaqti",
    delivered: "Yetkazilgan",
    empty: "Hali sizda buyurtmalar yo'q",
    emptyMessage:
      "Biz sizda hali buyurtmalar yo'qligini sezdik. Bu biroz tushkunlikka olib kelishi mumkin, lekin xavotir olmang, yangi buyurtmalar tez orada paydo bo'ladi",
    emptyRefresh: "Ro'yxat bo'sh, sahifani yangilang",
    status: {
      delivered: "Yetkazildi",
      arrived: "Yetib keldi",
      onWay: "Yo'lda",
      delayed: "Kechiktirildi",
      preparing: "Tayyorlanyapti",
      ready: "Tayyor",
      preparingMessage:
        "Buyurtma tayyorlanmoqda, tayyorlanishning oxirini kuting",
      checkAndStart:
        "Buyurtma pozitsiyalarini tekshirib, buyurtmani yetkazib berishni boshlang",
    },
    queueWarning:
      "Sizda buyurtmalar tartibini tahrirlash uchun bir daqiqa bor, shundan so'ng o'zgarmaydi",
    pressAtBranch:
      'Buyurtmalar olishni boshlash uchun "Men filialdaman" tugmasini bosing',
    timer: "Buyurtma taymeri:",
    order: "Buyurtma",
    total: "Jami:",
    address: "Manzil:",
    house: "Uy:",
    apartment: "Kvartira:",
    entrance: "Podyezd:",
    floor: "Qavat:",
    intercom: "Domofon kodi:",
    channel: "Buyurtma manbasi",
    paymentAmount: "To'lov summasi:",
    paymentMethod: "To'lov usuli:",
    paymentIndicatorPaid: "To'langan",
    paymentIndicatorNotPaid: "To'lanmagan",
    noComments: "Izohsiz:",
    comment: "Izoh",
    printTime: "Buyurtma vaqti",
    deliveryTime: "Yetkazib berish vaqti",
    startTime: "Boshlanish vaqti:",
    endTime: "Tugash vaqti:",
    addressChanged: "Manzil muvaffaqiyatli o'zgartirildi",
    addressError:
      "Mijoz manzilini o'zgartirishda xatolik yuz berdi, so'rovni qaytaring",
    changeAddress: "Manzilni almashtirish",
    addressWarning:
      "Manzil o'zgartirilishi operator tomonidan tekshiriladi va har bir buyurtma uchun manzil faqat bir marta o'zgartirilishi mumkin",
    showRoute: "Yo'lni ko'rsatish",
    arrive: "Yetib keldim",
    complete: "Yakunlash",
    delay: "Kechiktirish",
    startJourney: "Yo'lga chiqish",
    delayWarning:
      'Buyurtma %{allowedDelayedTime} minutdan ortiq "Kechiktirilgan". Buyurtma qabul qilishda davom etish uchun, joriy buyurtma(lar)ni mijozga yetkazing yoki filial rahbariga murojaat qiling.',
    finishDelayed: "Kechiktirilgan buyurtmalarni yakunlang",
    delayLimitWarning:
      "Buyurtma %{time} daqiqadan ko'proq \"Kechiktirilgan\" holatda bo'lishi mumkin emas. Shuningdek, kechiktirilgan buyurtmalar maksimal soni %{count} dona.",
    deliveredIn: "Yetkazib berildi",
    courierReady: "Kuryer buyurtmani olishga tayyor",
    finishDelivery: "Yetkazib berishni tugatish",
    atBranch: "Men filialdaman",
    distanceFromPoint: "Nuqtadan haqiqiy radius",
    notInRadius: "Siz mijoz radiusida emassiz",
  },
  profile: {
    status: {
      notInBranch: "Hali o'z filialingizga yetib bormadingiz",
    },
  },
  payment: {
    title: "To'lov",
    myPayments: "Mening to'lovlarim",
    selectType: "To'lov turini tanlang",
    cash: "Naqd pul",
    terminal: "Terminal",
    cards: "Kartalar",
    toCashier: "Kassaga:",
    page: "To'lov sahifasi",
    success: "Mijoz tomonidan to'lov muvaffaqiyatli amalga oshirildi",
    qrInstruction:
      "To'lovni amalga oshirish uchun mijozga QR-kodni taqdim eting",
    processing: "So'rovingiz bajarilmoqda, jarayon yakunlanganini tekshiring!",
    continueOrder: "Iltimos, davom etish uchun buyurtmaga o'ting!",
    smsSent: "Shuningdek, mijoz raqamiga to'lov haqida SMS-xabar yuborildi.",
    changeType: "To'lov turini o'zgartirish",
    fixed: "Fiksa",
    tips: "Choychaqa",
    bonus: "Bonus",
    penalty: "Jarima",
    amount: "Summa",
  },
  profile: {
    title: "Profil",
    language: "Til",
    rating: "Sizning reytingingiz",
    branch: "Sizning filialingiz:",
    distanceLeft: "Qolgan masofa:",
    selectBranch: "Filialni tanlang",
    changeBranch: "Filialni almashtirish",
    training: "Ta'lim",
    allCourses: "Barcha kurslar",
    courseRequired:
      "Sizga iSpring platformasida kurs biriktirilgan. Ushbu kursni o'tkazganingizdan so'ng, dasturdan foydalanishingiz mumkin!",
    status: {
      notStarted: "Boshlanmagan",
      inProgress: "Jarayonda",
      waiting: "Kutilmoqda",
      completed: "Yakunlandi",
      passed: "Topshirildi",
      incomplete: "To'liq emas",
      failed: "Muvaffaqiyatsiz",
      rejected: "Rad etildi",
      unknown: "Noma'lum",
      offline: "Ishlamayapti",
      onWay: "Yo'lda",
      onSite: "Yetib keldi",
      returning: "Qaytmoqda",
      assigned: "Biriktirilgan",
      free: "Bo'sh",
    },
    networkMonitoring: "Tarmoq monitoringi",
    determining: "Aniqlanmoqda...",
    numberDetermining: "Raqam aniqlanmoqda...",
    endShift: "Smenani yopish",
    activeOrdersWarning: "Sizda faol buyurtmalar bor!",
    enterSmsCode: "SMS orqali olingan kodni kiriting:",
    smsCodeSent:
      "Pin-kod allaqachon telefoningizga yuborilgan, iltimos, yana bir bor tekshiring",
    enterDifferentNumber: "Boshqa raqamni kiritish",
    pushError: "Push-bildirishnoma uchun token olish muvaffaqiyatsiz tugadi!",
    contactOperator: "Buyurtma bo'yicha operator bilan bog'lanish",
    noNearbyBranches:
      "Sizdan 150 m radiusda filiallar yo'q. Filialni o'zgartirish uchun filial radiusida bo'lishingiz kerak",
    organizationsNotFound: "Tashkilotlar topilmadi",
    nearestBranches: "Joylashuvingiz yaqinidagi eng yaqin filiallar",
    generalStats: "Umumiy statistika",
    averageRating: "%{reviewCount} ta sharh uchun o'rtacha reyting",
    ratingsAndCategories: "Reyting va kategoriyalar",
    total: "Umumiy soni",
    noRatingsWithScore: "Bu ball bilan sharhlar yo'q",
    noRatingsForPeriod: "Bu davr uchun sharhlar yo'q",
    organizationChanged: "Filial muvaffaqiyatli o'zgartirildi",
  },
  welcome: {
    title: "Xush kelibsiz!",
    motivationQuote:
      "Agar biror narsaga qodir ekanligingizga ishonsangiz, to‘g‘ri; agar muvaffaqiyatsiz bo‘laman desangiz, ham to‘g‘ri.",
  },
};

const option = local;
switch (option) {
  case "uz":
    output.local = uz;
    break;
  case "ru":
    output.local = ru;
    break;
  case "kz":
    output.local = kz;
    break;
}
